### ISSUE TITLE
GetAPNSToken returns null on some IOS devices

### ISSUE THREAD

**Issue by AydinKaya80** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#132]
GetAPNSToken working well while I'm testing on several devices. But on some users it returns null token.

**Comment by BRadHoc** [comment]
Use the FCM token instead, it works the same.

**Comment by andrehtissot** [comment]
@AydinKaya80 did you consider, after opening the app, waiting a minute before executing `GetAPNSToken()`? It might be that the app has not yet retrieved a APNS token.

@AydinKaya80 Would you share a table like:
|iOS version|Received APNS token|Received FCM token|
|-|-|-|
|X.X.X|Yes|Yes|
|X.X.X|No|Yes|
|X.X.X|No|NO|
|...|...|...|

**Comment by AbdullaevTimur** [comment]
Have the same issue. iOS 12.4.6 iPhone 6 Plus (ASPN Token = NO, FCM Token = Yes)

**Comment by AydinKaya80** [comment]
> @AydinKaya80 did you consider, after opening the app, waiting a minute before executing `GetAPNSToken()`? It might be that the app has not yet retrieved a APNS token.
> 
> @AydinKaya80 Would you share a table like:
> 
> iOS version	Received APNS token	Received FCM token
> X.X.X	Yes	Yes
> X.X.X	No	Yes
> X.X.X	No	NO
> ...	...	...

Ok, I will try to wait longer and let you know what will happen. Because when I am testing on my testin ios devices and emulator there is no problem. I need to go live to test it. Thanks for advance.

**Comment by andrehtissot** [comment]
Also @AbdullaevTimur  and @AbdullaevTimur,
If you grab the native log, you should see "Device APNS Token: [token]" (as expected on line https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/ios/AppDelegate%2BFCMPlugin.m#L85)

If you do see it in the native log, than it's a JS bug or calling the getter before the value is defined.
If you don't see it in the native log, it might be:
- a plugin error;
- incompatible certification error;
- running on a simulator, instead of a real device;
- application not configure to allow remote-notification on background (should be automatic on install);
- a network (very unlikely, but possible);

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
