### ISSUE TITLE
FCM.onNotification is not triggered when app is killed

### ISSUE THREAD

**Issue by SharathHuddar** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#138]
I am trying this on android. Everything is working as expected when the app is in the foreground or background.
However, when the app is killed, I expect onNotification to be triggered when the user taps on the notification. However, this does not happen.

I need this to handle deep links and redirect the user to the relevant page. However, when the app is killed and the user taps on the notification, the user is sent to the home page

**Comment by itziks00** [comment]
Hi,
You should use getInitialPushPayload method to receive the push payload that was received when the app was killed, since the onNotification wasn't registered yet.
Use version 7.0.9 latest. I used initially 7.0.3 but this method worked only on android.

**Comment by itziks00** [comment]
BTW, @andrehtissot, When I moved from 7.0.3 to 7.0.9 I got an issue during 'cordova platform add ios' and I found that the cause is the change in plugin.xml:
from: **<source url="https://cdn.cocoapods.org"/>**
to: **<source url="https://github.com/CocoaPods/Specs.git"/>**

I'm using the plugin on 2 projects:

- One project is only with cordova, and with the new source url when running 'platform add ios', right after it adds this fcm plugin, and 'Running command: pod install" it thrown an error:
`19:50:06 Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
19:50:08 Running command: pod install --verbose
19:50:09 Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 31
19:50:09     at ChildProcess.whenDone (/Users/FrontendJenkins/.jenkins/workspace/_WeR_Production/mobile/node_modules/cordova-common/src/superspawn.js:135:23)
19:50:09     at emitTwo (events.js:106:13)
19:50:09     at ChildProcess.emit (events.js:191:7)
19:50:09     at maybeClose (internal/child_process.js:877:16)
19:50:09     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19:50:09 pod: Command failed with exit code 31`

- The other project is Ionic with cordova, and with the new source url when running 'platform add ios', right after it adds this fcm plugin, and 'Running command: pod install" it just hangs on this message:
`Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Cloning into' cocoapods'...`

So I'm using version 7.0.9 but with the old url - <source url="https://cdn.cocoapods.org"/>
is it ok?
Thanks.

**Comment by SharathHuddar** [comment]
This helps. Thanks a lot

**Comment by stsness** [comment]
>  If the subscription to notification events happens after the notification has been fired, it'll be lost. As it is expected that you'd not always be able to catch the notification payload that the opened the app, the FCM.getInitialPushPayload() method was introduced."

With getInitialPushPayload() I always get null result...  
In some states are normal but after kill app, open notification then open app and it must return payload if I am not wrong
I am testing over ionic V3 example of this plugin. What is it happening?
