### ISSUE TITLE
Question: Android permission

### ISSUE THREAD

**Issue by bwojtyca** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#140]
Hey,

Is there a way to check the "real" permissions status on Android to retrieve notifications?

From what I understand there are at least a few scenarios when push notification will be not retrieved:
- user blocked notification in application settings
- user blocked some categories (channels) in application settings
- user blocked background data
- user's battery optimization is blocking push notifications
- user's device manufacturer is killing background tasks to reduce battery consumption

and at the same time, this plugin is always returning `true` from the method `hasPermissions` on Android...

I'm curious if it's possible to (with this plugin) check if any of the cases described above are valid for the user... Or perhaps you can suggest some other solution(-s)?

**Comment by andrehtissot** [comment]
I wanted to confirm something...

Giving that you found that this app has permission, even considering all the conditions you mentioned.

How long would you assume the permission is still available?

**Comment by bwojtyca** [comment]
I'm not sure if I understand...

I don't want to assume anything... I'm rather looking for solution that will give me a clear information that push notifications are working on user's device. And in case that something (ex. user's settings) is blocking push notifications I would like to display a clear indication about that to the user.

At the moment, in my app under push notifications settings I'm providing, I've placed a link to the article how user can solve potential issues on his side. But I think this is not the most elegant way and I would like to be more specific for the users.

**Comment by andrehtissot** [comment]
If you don't want to assume _anything_.
I would, in your case, always send the Push.
If the user taps on it, I would send the confirmation to a server to established that it was received.
To avoid false negatives, I would send this confirmation with native code, right away when it's retrieved instead of when it's tapped.


If you check one time if push is available. It might not be when you decide to send the puhs.
Hence using cordova-diagnostic-plugin.isRemoteNotificationsEnabled(), does imply that you assume that the user won't change his/hers notification options between those two points in time.

**Comment by bwojtyca** [comment]
@andrehtissot that's a very clever sneaky idea I didn't think of :) Thanks for the suggestion!
