### ISSUE TITLE
data.wasTapped don't execute any action

### ISSUE THREAD

**Issue by jorgehenriquezd** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#144]
```typescript
this.fcm.onNotification().subscribe(data => {
	if (data.wasTapped) {
		this.router.navigate(['chat-user-admin']);
		this.newMessage.next(this.newMessage.value + 1);
	} else {
		this.newMessage.next(this.newMessage.value + 1);
		this.showToast('New Message');
	};
});
```

The actions below data.wasTapped don't work
ionic version 6.10.1

**Comment by andrehtissot** [comment]
@jorgehenriquezd 
What do you mean by "don't work"?
Would you describe step-by-step your actions, the behavior seen and the expected behavior?

**Comment by marcelocch** [comment]
Hi @andrehtissot I'm having a similar problem.
The push notification sent shows when app is closed or on background, but when is open it doesn't get the payload title or body and I cant show it on my custom alert dialog because of that. (It works perfectly on Android)
`this.fcm
      .onNotification()
      .subscribe((payload: any) => {
//payload.title and payload.body are null and my alert shows only the custom button "Entendido" with no texts from the payload.
        this.alert.presentAlert(payload.title, payload.body);
      });`
Here is what I was talking about, since payload.title and payload.body are null, it only shows the alert with no text.
![image](https://user-images.githubusercontent.com/38540410/90165643-94b86c00-dd5e-11ea-8518-c015cd6ac00c.png)

My IONIC info: 
`Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/marcelocch/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.14.6
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708`
My cordova plugins installed:
`cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm-with-dependecy-updated 7.0.9 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 3.0.4 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"`

**Comment by AngelBarrera** [comment]
Same here, when app is in foreground or background the onNotification works (calling wasTapped if App open from Notification) but when App is closed and the user clicks in the push notification the App open but onNotification or getInitialPushPayload didn't works

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.

@AngelBarrera: Your comment will be addressed as a new issue, as it presents much more information and what you are facing may not relate to this specific issue.
