### ISSUE TITLE
On ios platform could not install plugin

### ISSUE THREAD

**Issue by iChristosK** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#77]
I am trying to install this plugin using the command 
`ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated` (which by the way the word **dependency** is incorrectly written) but it fails, with the following error 
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': undefined
CordovaError: Promise rejected with non-error

I provide the screenshot with the full error below. 
![Screenshot 2020-05-22 at 16 49 28](https://user-images.githubusercontent.com/16455384/82675419-735b4e80-9c4d-11ea-9f88-636561be260c.png)

My Ionic Info
![Screenshot 2020-05-22 at 16 54 20](https://user-images.githubusercontent.com/16455384/82675298-4a3abe00-9c4d-11ea-97f9-fcd18a6b124a.png)

Below are my dependencies from package.json.

```

"@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/background-mode": "^5.26.0",
    "@ionic-native/call-number": "^5.26.0",
    "@ionic-native/camera": "^5.26.0",
    "@ionic-native/chooser": "^5.25.0",
    "@ionic-native/core": "^5.25.0",
    "@ionic-native/device": "^5.26.0",
    "@ionic-native/diagnostic": "^5.26.0",
    "@ionic-native/file": "^5.26.0",
    "@ionic-native/file-chooser": "^5.26.0",
    "@ionic-native/file-opener": "^5.26.0",
    "@ionic-native/file-path": "^5.26.0",
    "@ionic-native/file-picker": "^5.26.0",
    "@ionic-native/file-transfer": "^5.26.0",
    "@ionic-native/geolocation": "^5.26.0",
    "@ionic-native/google-maps": "^5.0.0-beta.27",
    "@ionic-native/media": "^5.26.0",
    "@ionic-native/media-capture": "^5.26.0",
    "@ionic-native/native-storage": "^5.26.0",
    "@ionic-native/splash-screen": "^5.26.0",
    "@ionic-native/status-bar": "^5.26.0",
    "@ionic-native/streaming-media": "^5.26.0",
    "@ionic-native/theme-detection": "^5.26.0",
    "@ionic-native/toast": "^5.25.0",
    "@ionic-native/touch-id": "^5.25.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.2.0",
    "angular-oauth2-oidc": "^9.2.2",
    "angular-oauth2-oidc-jwks": "^9.0.0",
    "call-number": "^1.0.1",
    "cordova-common": "^4.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-add-swift-support": "2.0.2",
    "cordova-plugin-background-mode": "0.7.3",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-chooser": "1.3.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filechooser": "^1.2.0",
    "cordova-plugin-filepath": "^1.5.8",
    "cordova-plugin-filepicker": "^1.1.6",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-googlemaps": "^2.7.1",
    "cordova-plugin-googlemaps-sdk": "file:../../cordova-plugin-googlemaps-sdk",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-media": "^5.0.3",
    "cordova-plugin-media-capture": "^3.0.3",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-streaming-media": "^2.2.0",
    "cordova-plugin-theme-detection": "1.2.1",
    "cordova-plugin-touch-id": "3.4.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-toast": "^2.7.2",
    "cordova-sqlite-storage": "^5.0.0",
    "cordova.plugins.diagnostic": "^5.0.2",
    "core-js": "^2.5.4",
    "crypto-js": "^4.0.0",
    "ngx-socket-io": "^3.0.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"

```

**Comment by andrehtissot** [comment]
The typo in the name is known. But, tbh, having it working properly and having useful features is higher priority for me than having a good name. Which now, the plugin has been more stable than ever, can be worked on without breaking people's projects due to, in some cases, been referencing the url which contains the typo.

The error you pointed out is related to this plugin, but not really something I can fix. Altough I can explain the issue, thanks to your error log.

This plugin, makes use of cocoapods, which handles the google dependencies.

If you read the error message, it just says that you shouldn't run cocoapods as root (by running with `sudo`).
It is frowned upon to run dependency installs as root, as you are installing from many sources with many authors, which presents some risk. And, as root, the scripts' access, and therefore the risk, is even higher.

So I'd recommend to run the command as you mentioned `ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated`, without sudo.
