### ISSUE TITLE
Firebase Messaging iOS SDK v7.0 will no longer support the FCM Direct Channel API

### ISSUE THREAD

**Issue by almiraputrisandy** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#78]
Hey guys, I received an email from Firebase with the above subject. I was wondering if this is because I have not updated the plugin? My plugin version is 4.1.1. This is the full email for reference:

> We are writing to let you know that Firebase Messaging iOS Direct Channel API support is marked for deprecation. Firebase Messaging iOS SDK version 7.0 will be a breaking change where the SDK will no longer support iOS Direct Channel API.

> What do I need to know?
> Firebase Messaging iOS Direct Channel has been used for sending data to apps when they are in the foreground and for upstream messages. The Firebase Messaging iOS SDK v7.0 (slated to be released in September 2020) will no longer support the iOS Direct Channel API. Your app will break if you update to the Firebase Messaging iOS SDK v7.0 without migrating off the iOS Direct Channel API.

> We are removing this feature in favor of natively supported messaging features provided by Apple Push Notification Service.

> To prevent disruptions to your users, we recommend that you discontinue use of the iOS Direct Channel API as soon as possible. Please note that for the time being, your existing users can still continue to receive messages via the iOS Direct Channel API. However, within the next year, we will follow up this announcement with plans to deprecate the backend service support which may break your app with older versions of the Messaging iOS SDK (prior to v7.0).

> What do I need to do?
>  - To prevent disruptions to your users, we recommend that you discontinue use of the iOS Direct Channel API and use an alternative such as FCM’s APNs interface for downstream data message delivery.
> - If you are not using FCM HTTP v1 API, we strongly recommend that you do so. FCM HTTP v1 API provides full APNs support. If you need to continue using FCM Legacy API, you can:
> - Add the `content_available` key to your payload if you continue to use the legacy sender API.
> - For upstream messages, make arrangements to send messages directly from your app to your servers.
> - For real time updates, you can use Cloud Firestore, Realtime Database, or other services.

**Comment by andrehtissot** [comment]
**For the app side:**
Nothing should break, unless you were using the briefly supported `onFirebaseDataNotificationIOS`.

Since v5, all the deprecated iOS Direct Channel API methods were removed from this plugin.

But it's always recommended to keep up with the newer versions, currently v6.4.0.

When you update the `cordova-plugin-fcm-with-dependecy-updated`, please don't forget to add the call to request user's push permission `requestPushPermissionIOS();`, which now doesn't have to be at start.



**From the server side**
I'd have to know how do you send the push payloads to FCM.
From the email, it recommends, that you use the FCM HTTP v1 API (https://firebase.google.com/docs/cloud-messaging/server https://firebase.google.com/docs/cloud-messaging/migrate-v1).


If there is any questions, let me know.

**Comment by almiraputrisandy** [comment]
Hey! this is how I did it on the server side. I'm pretty sure it uses the FCM HTTP v1 API
```
var FCMAdmin = require("firebase-admin");
var FCMServiceAccount = require("./service-account.json");
var topic = req.body.target;

var payloadWithTopic = {
    'notification': {
        'title': req.body.title,
        'body': req.body.message
    },
    topic: topic
};

FCMAdmin.messaging().send(payloadWithTopic)
        .then(function(response) {
            console.log("Topic message sent successfully");
        }).catch(function(err) {
            console.log(err);
        });
```

I tried to update the plugin by removing and adding the plugin to my project again, but when re-adding the plugin I encountered an error. Something like `ruby gems 2.7.0 cocoapods-core 1.9.2 URI.escape is obsolete` and `Error: pod: Command failed with exit code 31`. So, I reverted all changes by running `git reset head --hard` and discarding all new files that were created from removing and adding the plugin using GitHub Desktop. But now when I run my app on my iPhone 7 Plus, I'm not receiving any push notifications, despite the log says "subscribe to topic successful" and being able to receive the APNS token. When I put the app in the background, the log says 'Disconnected from FCM' and `FIRMessaging received data message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`.

What could be the problem? Everything was working fine until I tried to update the plugin. It even works when I install a previous build from Testflight.

**Comment by almiraputrisandy** [comment]
So I've managed to update the plugin. I re-installed cocoapods and ran `pod setup` before removing and re-adding the plugin. I added the `requestPushPermissionIOS();` function when initializing my app like this:

```
var app = new Framework7({
	root: '#app', // App root element
	id: 'io.framework7.appname', // App bundle ID
	name: 'App Name', // App name
	theme: 'auto', // Automatic theme detection
	// App routes
	routes: routes,
	// Input settings
	input: {
		scrollIntoViewOnFocus: Framework7.device.cordova && !Framework7.device.electron,
		scrollIntoViewCentered: Framework7.device.cordova && !Framework7.device.electron,
	},
	// Cordova Statusbar settings
	statusbar: {
		iosOverlaysWebView: true,
		androidOverlaysWebView: false,
	},
	on: {
		init: function () {
			var f7 = this;
			if (f7.device.cordova) {
				// Init cordova APIs (see cordova-app.js)
				cordovaApp.init(f7);
				FCMPlugin.requestPushPermissionIOS(function(wasPermissionGiven) {
					console.log("Was permission given: "+wasPermissionGiven);
					window.localStorage.setItem('hasPermission', wasPermissionGiven);
				  },
				  function(error) {
					console.error(error);
				  }
				);
			}
		},
	},
});
```

And then call the `subscribeToTopic();` function when the login button is clicked. In my Xcode logs, permission given returns true and subscribe to topic is successful, but I am unable to receive push notifications when app is in the background? Any idea why?

**Comment by andrehtissot** [comment]
That's certainly strange.

Would you:
1. Try to send a push notification by token, instead of topic, just as a test?
2. Share your ios' runtime log?
3. Share your package.json?
4. Share the version(s) of the iOS you are running your app on?

**Comment by almiraputrisandy** [comment]
I'll try to send push notification by token and update you later, along with the runtime log. I'm running on iOS 13.4.1. This is my package.json:

```
{
  "name": "bundleid",
  "displayName": "App Name",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {
    "cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-fcm-with-dependecy-updated": "^6.4.0",
    "cordova-plugin-keyboard": "^1.2.0",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-wkwebview-engine": "^1.2.1",
    "cordova-plugin-wkwebview-file-xhr": "^2.1.3"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-keyboard": {},
      "cordova-plugin-wkwebview-file-xhr": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-wkwebview-engine": {},
      "cordova-plugin-fcm-with-dependecy-updated": {
        "FCM_VERSION": "19.0.0",
        "GRADLE_TOOLS_VERSION": "3.5.3",
        "GOOGLE_SERVICES_VERSION": "4.3.3",
        "SUPPORT_LIBRARY_VERSION": "28.0.0",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher"
      }
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  }
}
```

**Comment by almiraputrisandy** [comment]
I logged in to my app and sent notification via topic, and magically, it works? all I changed was adding

```
FCMPlugin.onNotification(function(data){
        console.log(JSON.stringify(data));
});

FCMPlugin.onNotificationReceived(function(payload){
        console.log(JSON.stringify(payload));
});
```

But I don't understand why that would affect it because I can receive push notification without implementing the above in the previous version?

**Comment by andrehtissot** [comment]
The method `FCMPlugin.onNotificationReceived` shouldn't be called from the app.
Calling the `FCMPlugin.onNotification` with a callback as argument should not cause this impact.


It looks a bit absurd, unless this is somewhat test/debugging code not coming from the plugin itself. As the log suggests:
```
2020-05-24 16:26:34.913209+0800 Trienekens[1288:254944] Device FCM Token: FCM token
2020-05-24 16:26:34.913327+0800 Trienekens[1288:254944] notifyFCMTokenRefresh token: FCM token
2020-05-24 16:26:34.913382+0800 Trienekens[1288:254944] stringByEvaluatingJavaScriptFromString FCMPlugin.onTokenRefreshReceived('FCM token');
2020-05-24 16:26:34.916172+0800 Trienekens[1288:254944] Received token refresh
2020-05-24 16:26:34.916334+0800 Trienekens[1288:254944] FCM token
2020-05-24 16:26:36.996415+0800 Trienekens[1288:254944] Device APNS Token: token
```

APNS token would never be "token" and FCM token would never be "FCM token". 🧐

**Comment by almiraputrisandy** [comment]
why shouldn't `FCMPlugin.onNotificationReceived` be called from the app?

also, I purposely change the value of APNS and FCM token values for this purpose, the actual value is a real token

**Comment by andrehtissot** [comment]
> why shouldn't FCMPlugin.onNotificationReceived be called from the app?

Because, the native implementation calls `FCMPlugin.onNotificationReceived(token)`.
So as you can see in the javascript file https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/www/FCMPlugin.js

`onNotificationReceived` is the callback function that is called _with_ the token.
```javascript
FCMPlugin.prototype.onNotificationReceived = function (payload) {
  console.log("Received push notification");
  console.log(payload);
};
```

While `onNotification` just replaces the default function above with the one given as argument.
```javascript
FCMPlugin.prototype.onNotification = function (callback, success, error) {
  FCMPlugin.prototype.onNotificationReceived = callback;
  exec(success, error, "FCMPlugin", "registerNotification", []);
};
```

I'm sure that these definitions could be much better, and I'll probably refactor it with more convenient solutions like observables and promises. And make more clear which methods are internal and which are the supported for public use. It's just been kept for legacy reasons.

> also, I purposely change the value of APNS and FCM token values for this purpose, the actual value is a real token

It got me confused. For those cases I usually replace with "[REDACTED]".

... but still, don't know why it would fail without calling `onNotification`. Maybe it just took some time to relate that toked id to a topic? I did check the ios' implementation of the above mentioned registerNotification method, but there was nothing that would "activate" the plugin or anything.

**Comment by almiraputrisandy** [comment]
yeah, maybe I didn't give it enough time for the token to subscribe to a topic. I'll remove `FCMPlugin.onNotificationReceived()` and try again later and let you know the result. Thanks for all the information you've given me!

**Comment by andrehtissot** [comment]
Thank you for reaching out.

I'll close as there is nothing much to go on and you got it working.

If you get any issues, let me know.

**Comment by almiraputrisandy** [comment]
Hi, just want to update you that I can still receive push notification even when `FCMPlugin.onNotificationReceived()` and `FCMPlugin.onNotification()` are removed. I guess the problem was not giving it enough time to subscribe to a topic after all

**Comment by andrehtissot** [comment]
Thank you for letting me know.

If you face other issues, I'm here.

**Comment by itziks00** [comment]
Hi,

I was using this plugin, until I had issues of conflicts with 'cordova-plugin-local-notifications', and I saw a suggestion to switch to the fork of this plugin - **https://github.com/Shashank2406/cordova-plugin-fcm-with-dependency-updated-apns** and all issues were resolved.

Now, I got the same email described in this issue "Firebase Messaging iOS SDK v7.0 will no longer support the FCM Direct Channel API".
I'm not sure what should I do... and if something will be deprecated on the forked plugin...
There is no option to ask there.

Any idea? 
Thanks!

**Comment by andrehtissot** [comment]
Thank you for linking the fork. Unfortunately, it is based on v2.4.0, which although was quite good for the time, it does still implements deprecated SDK features and lack many current features.

What @Shasheank2406 has included, that the current plugin of `cordova-plugin-fcm-with-dependecy-updated` doesn't contain, is to present the notification when received. Instead of giving it to the JS context, and, from the JS context, calling something like `cordova-plugin-local-notifications`.

@Shasheank2406's approach is by consequence a little more performant, but it has the downside of restricting how the app, in the JS context, handles the notification event and how it chooses to present the notification.

Using @Shasheank2406's fork is not recommended, but can serve until the incompatibility with current `cordova-plugin-local-notifications` is fixed.

Just to understand a bit better your specific case. How were you using `cordova-plugin-local-notifications` and on which version.

**Comment by itziks00** [comment]
@andrehtissot, thank you very much for your answer!
Our app is using Ionic 3.
We're using `cordova-plugin-local-notifications` version 0.9.0-beta.3.
The usage is for showing notifications on the foreground on iOS. 
When the `onNotification()` callback is being received, we call the local notification plugin to show notification on iOS. Otherwise we couldn't solve showing notifications on the foreground for iOS.

I remember that initially I was using this specific plugin, and there was a conflict with the local notifications plugin, so after searching, I found the below suggestions which suggested to replace it.

- https://github.com/katzer/cordova-plugin-local-notifications/issues/1759
- https://github.com/fechanique/cordova-plugin-fcm/issues/509
- https://forum.ionicframework.com/t/ionic-3-local-notification-not-working-in-ios-with-fcm/147377/5

Meantime it's working perfect, but after getting this email from google Firebase, I wasn't sure if this fork includes code that won't be supported soon.
I understand that there are things to modify on our Backend, but on the plugin I wasn't sure if there is deprecated code.

Thanks.

**Comment by itziks00** [comment]
@andrehtissot Thanks a lot, I appreciate it!
I will check and update.
