### ISSUE TITLE
[Question] on iOS should getToken or getAPNSToken be used?

### ISSUE THREAD

**Issue by gaurav-chandra** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#87]
if we are using FCM for iOS, should getToken or getAPNSToken be used?

**Comment by RichardBoyder** [comment]
getToken works for me. Seems you don’t need APNSToken, But you have to remember to make sure in your info.plist this is there set to no:

**Comment by gaurav-chandra** [comment]
@RichardBoyder what is the setting which needs to be set to no?

**Comment by RichardBoyder** [comment]
FirebaseAppDelegateProxyEnabled.  Boolean.    No 

That’s in your info.plist .

The plugin actually should do that for you automatically so if installed in Xcode you should see that.

**Comment by andrehtissot** [comment]
getToken() retrieves the Firebase Token. getAPNSToken() retrieves the Apple Push Notification Service token. Depending on your 3rd party integrations you might need one or the the other.

FirebaseAppDelegateProxyEnabled should be disabled as default. Since the app itself is handling the firebase setup itself, as proxying was too unreliable. 

This plugin should set FirebaseAppDelegateProxyEnabled as False on install, hence the log message.
